/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author oscarfh06
 */
public class Calculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculadora.class.getName());

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pantallaCalculadora = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        buttonNueve = new javax.swing.JButton();
        buttonSeis = new javax.swing.JButton();
        buttonOcho = new javax.swing.JButton();
        buttonSiete = new javax.swing.JButton();
        ButtonUno = new javax.swing.JButton();
        buttonCinco = new javax.swing.JButton();
        buttonCuatro = new javax.swing.JButton();
        buttonTres = new javax.swing.JButton();
        buttonDos = new javax.swing.JButton();
        buttonIgual = new javax.swing.JButton();
        buttonSumar = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        buttonDividir = new javax.swing.JButton();
        buttonMultiplicar = new javax.swing.JButton();
        buttonRestar = new javax.swing.JButton();
        buttonCero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 224, 213));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantallaCalculadora.setEditable(false);
        pantallaCalculadora.setBackground(new java.awt.Color(255, 255, 255));
        pantallaCalculadora.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        pantallaCalculadora.setForeground(new java.awt.Color(0, 0, 0));
        pantallaCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallaCalculadoraActionPerformed(evt);
            }
        });
        jPanel1.add(pantallaCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 333, 130));

        jPanel2.setBackground(new java.awt.Color(153, 224, 213));

        buttonNueve.setBackground(new java.awt.Color(51, 153, 255));
        buttonNueve.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        buttonNueve.setForeground(new java.awt.Color(0, 0, 0));
        buttonNueve.setText("9");
        buttonNueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNueveMouseClicked(evt);
            }
        });
        buttonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNueveActionPerformed(evt);
            }
        });

        buttonSeis.setBackground(new java.awt.Color(51, 153, 255));
        buttonSeis.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        buttonSeis.setForeground(new java.awt.Color(0, 0, 0));
        buttonSeis.setText("6");
        buttonSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSeisMouseClicked(evt);
            }
        });
        buttonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeisActionPerformed(evt);
            }
        });

        buttonOcho.setBackground(new java.awt.Color(51, 153, 255));
        buttonOcho.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        buttonOcho.setForeground(new java.awt.Color(0, 0, 0));
        buttonOcho.setText("8");
        buttonOcho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOchoMouseClicked(evt);
            }
        });
        buttonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOchoActionPerformed(evt);
            }
        });

        buttonSiete.setBackground(new java.awt.Color(51, 153, 255));
        buttonSiete.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        buttonSiete.setForeground(new java.awt.Color(0, 0, 0));
        buttonSiete.setText("7");
        buttonSiete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSieteMouseClicked(evt);
            }
        });
        buttonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSieteActionPerformed(evt);
            }
        });

        ButtonUno.setBackground(new java.awt.Color(51, 153, 255));
        ButtonUno.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        ButtonUno.setForeground(new java.awt.Color(0, 0, 0));
        ButtonUno.setText("1");
        ButtonUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonUnoMouseClicked(evt);
            }
        });
        ButtonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUnoActionPerformed(evt);
            }
        });

        buttonCinco.setBackground(new java.awt.Color(51, 153, 255));
        buttonCinco.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        buttonCinco.setForeground(new java.awt.Color(0, 0, 0));
        buttonCinco.setText("5");
        buttonCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCincoMouseClicked(evt);
            }
        });
        buttonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCincoActionPerformed(evt);
            }
        });

        buttonCuatro.setBackground(new java.awt.Color(51, 153, 255));
        buttonCuatro.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        buttonCuatro.setForeground(new java.awt.Color(0, 0, 0));
        buttonCuatro.setText("4");
        buttonCuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCuatroMouseClicked(evt);
            }
        });
        buttonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCuatroActionPerformed(evt);
            }
        });

        buttonTres.setBackground(new java.awt.Color(51, 153, 255));
        buttonTres.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        buttonTres.setForeground(new java.awt.Color(0, 0, 0));
        buttonTres.setText("3");
        buttonTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTresMouseClicked(evt);
            }
        });
        buttonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTresActionPerformed(evt);
            }
        });

        buttonDos.setBackground(new java.awt.Color(51, 153, 255));
        buttonDos.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        buttonDos.setForeground(new java.awt.Color(0, 0, 0));
        buttonDos.setText("2");
        buttonDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDosMouseClicked(evt);
            }
        });
        buttonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDosActionPerformed(evt);
            }
        });

        buttonIgual.setBackground(new java.awt.Color(51, 153, 255));
        buttonIgual.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        buttonIgual.setForeground(new java.awt.Color(0, 0, 0));
        buttonIgual.setText("=");
        buttonIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonIgualMouseClicked(evt);
            }
        });
        buttonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIgualActionPerformed(evt);
            }
        });

        buttonSumar.setBackground(new java.awt.Color(51, 153, 255));
        buttonSumar.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        buttonSumar.setForeground(new java.awt.Color(0, 0, 0));
        buttonSumar.setText("+");
        buttonSumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSumarMouseClicked(evt);
            }
        });
        buttonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSumarActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(51, 153, 255));
        jButton12.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("CE");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        buttonDividir.setBackground(new java.awt.Color(51, 153, 255));
        buttonDividir.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        buttonDividir.setForeground(new java.awt.Color(0, 0, 0));
        buttonDividir.setText("÷");
        buttonDividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDividirMouseClicked(evt);
            }
        });
        buttonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDividirActionPerformed(evt);
            }
        });

        buttonMultiplicar.setBackground(new java.awt.Color(51, 153, 255));
        buttonMultiplicar.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        buttonMultiplicar.setForeground(new java.awt.Color(0, 0, 0));
        buttonMultiplicar.setText("x");
        buttonMultiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMultiplicarMouseClicked(evt);
            }
        });
        buttonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplicarActionPerformed(evt);
            }
        });

        buttonRestar.setBackground(new java.awt.Color(51, 153, 255));
        buttonRestar.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        buttonRestar.setForeground(new java.awt.Color(0, 0, 0));
        buttonRestar.setText("-");
        buttonRestar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRestarMouseClicked(evt);
            }
        });
        buttonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRestarActionPerformed(evt);
            }
        });

        buttonCero.setBackground(new java.awt.Color(51, 153, 255));
        buttonCero.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        buttonCero.setForeground(new java.awt.Color(0, 0, 0));
        buttonCero.setText("0");
        buttonCero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCeroMouseClicked(evt);
            }
        });
        buttonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(buttonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(buttonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ButtonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(buttonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(buttonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ButtonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 360, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pantallaCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallaCalculadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pantallaCalculadoraActionPerformed

    private void buttonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNueveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNueveActionPerformed

    private void buttonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSeisActionPerformed

    private void buttonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOchoActionPerformed

    private void buttonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSieteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSieteActionPerformed

    private void ButtonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonUnoActionPerformed

    private void buttonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCincoActionPerformed

    private void buttonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCuatroActionPerformed

    private void buttonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTresActionPerformed

    private void buttonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDosActionPerformed

    private void buttonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIgualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonIgualActionPerformed

    private void buttonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSumarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSumarActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void buttonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDividirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDividirActionPerformed

    private void buttonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMultiplicarActionPerformed

    private void buttonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRestarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRestarActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        pantallaCalculadora.setText("");
    }//GEN-LAST:event_jButton12MouseClicked

    private void buttonTresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTresMouseClicked
        // TODO add your handling code here:
        escribirNumero(3);
    }//GEN-LAST:event_buttonTresMouseClicked

    private void buttonDosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDosMouseClicked
        // TODO add your handling code here:
        escribirNumero(2);
    }//GEN-LAST:event_buttonDosMouseClicked

    private void ButtonUnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonUnoMouseClicked
        // TODO add your handling code here:
        escribirNumero(1);
    }//GEN-LAST:event_ButtonUnoMouseClicked

    private void buttonSeisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSeisMouseClicked
        // TODO add your handling code here:
        escribirNumero(6);
    }//GEN-LAST:event_buttonSeisMouseClicked

    private void buttonCuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCuatroMouseClicked
        // TODO add your handling code here:
        escribirNumero(4);
    }//GEN-LAST:event_buttonCuatroMouseClicked

    private void buttonSieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSieteMouseClicked
        // TODO add your handling code here:
        escribirNumero(7);
    }//GEN-LAST:event_buttonSieteMouseClicked

    private void buttonOchoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOchoMouseClicked
        // TODO add your handling code here:
        escribirNumero(8);
    }//GEN-LAST:event_buttonOchoMouseClicked

    private void buttonNueveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNueveMouseClicked
        // TODO add your handling code here:
        escribirNumero(9);
    }//GEN-LAST:event_buttonNueveMouseClicked

    private void buttonMultiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMultiplicarMouseClicked
        // TODO add your handling code here:
        escribirSimbolo("*");
        
    }//GEN-LAST:event_buttonMultiplicarMouseClicked

    private void buttonSumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSumarMouseClicked
        // TODO add your handling code here:
        escribirSimbolo("+");
    }//GEN-LAST:event_buttonSumarMouseClicked

    private void buttonRestarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRestarMouseClicked
        // TODO add your handling code here:
        escribirSimbolo("-");
    }//GEN-LAST:event_buttonRestarMouseClicked

    private void buttonDividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDividirMouseClicked
        // TODO add your handling code here:
        escribirSimbolo("/");
    }//GEN-LAST:event_buttonDividirMouseClicked

    private void buttonIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonIgualMouseClicked
        // TODO add your handling code here:
        ejecutarOperacion();
    }//GEN-LAST:event_buttonIgualMouseClicked

    private void buttonCeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCeroMouseClicked
        // TODO add your handling code here:
        escribirSimbolo("0");
    }//GEN-LAST:event_buttonCeroMouseClicked

    private void buttonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCeroActionPerformed

    private void buttonCincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCincoMouseClicked
        // TODO add your handling code here:
        escribirSimbolo("5");

    }//GEN-LAST:event_buttonCincoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculadora().setVisible(true));
    }
    
    private void escribirNumero(int numero){
        pantallaCalculadora.setText(pantallaCalculadora.getText() + numero);
    }
      private void escribirSimbolo(String simbolo){
        pantallaCalculadora.setText(pantallaCalculadora.getText() + simbolo);
    }

    private void ejecutarOperacion(){
        System.out.println((pantallaCalculadora.getText()));
        
        if (pantallaCalculadora.getText().isEmpty()) {
            System.out.println("Ingresa dígitos para operar");
            return;
        }
        
        if(pantallaCalculadora.getText().contains("+")){
           String[] sumaSeparada = pantallaCalculadora.getText().split("\\+");
           int suma = Integer.parseInt(sumaSeparada[0]) + Integer.parseInt(sumaSeparada[1]);
           pantallaCalculadora.setText(String.valueOf(suma));
        }
        else if (pantallaCalculadora.getText().contains("-")) {
            String[] sumaSeparada = pantallaCalculadora.getText().split("-");
            int resta = Integer.parseInt(sumaSeparada[0]) - Integer.parseInt(sumaSeparada[1]);
            pantallaCalculadora.setText(String.valueOf(resta));
        }
        else if (pantallaCalculadora.getText().contains("/")) {
            String[] sumaSeparada = pantallaCalculadora.getText().split("\\/");
            if(Integer.parseInt(sumaSeparada[0]) < Integer.parseInt(sumaSeparada[1]) || Integer.parseInt(sumaSeparada[1]) == 0){
                pantallaCalculadora.setText("Error");
                return;
            }
            int division = Integer.parseInt(sumaSeparada[0]) / Integer.parseInt(sumaSeparada[1]);

            pantallaCalculadora.setText(String.valueOf(division));
        }
        else if (pantallaCalculadora.getText().contains("*")) {
            String[] sumaSeparada = pantallaCalculadora.getText().split("\\*");
            int multiplicacion = Integer.parseInt(sumaSeparada[0]) * Integer.parseInt(sumaSeparada[1]);
            pantallaCalculadora.setText(String.valueOf(multiplicacion));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonUno;
    private javax.swing.JButton buttonCero;
    private javax.swing.JButton buttonCinco;
    private javax.swing.JButton buttonCuatro;
    private javax.swing.JButton buttonDividir;
    private javax.swing.JButton buttonDos;
    private javax.swing.JButton buttonIgual;
    private javax.swing.JButton buttonMultiplicar;
    private javax.swing.JButton buttonNueve;
    private javax.swing.JButton buttonOcho;
    private javax.swing.JButton buttonRestar;
    private javax.swing.JButton buttonSeis;
    private javax.swing.JButton buttonSiete;
    private javax.swing.JButton buttonSumar;
    private javax.swing.JButton buttonTres;
    private javax.swing.JButton jButton12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField pantallaCalculadora;
    // End of variables declaration//GEN-END:variables
}
